### ISSUE TITLE
Webhook Action - Pull Request Opened

### ISSUE THREAD

**Issue by johnsgill3** [CodeGovernor/CodeGovernor#24]
Handle actions for a PR that is opened

**Comment by johnsgill3** [comment]
@ryanbmilbourne Some questions I am having while working on this that I think discussion would be warranted.

1. When a file has the status 'added' how should we determine reviewer for the file?
     1. When should a new file get added to our backend? At PR open to track the review. Or at PR Closed/Merged?
1. Should 'deleted' files still be reviewed?
1. Are there any other possible statuses for a file like maybe 'renamed'?
1. Should we add a label to the PR indicating something like 'Pending Reviews' to help users filter?
1. Can a PR ever be opened without any file changes?
1. Should a feedback entry be added for each (review, file, user) or just (review, user)?

Any other thoughts you have about what we should do when a PR is opened please share.

**Comment by ryanbmilbourne** [comment]
1. Unless tagged otherwise via a PR thread comment, the owner of a file at creation should be the person who added it to the repo.  WRT to the 'when' of a file add, we could opt to create it after merge, but that would potentially mean that a new file wouldn't be reviewed by anybody.  We could add it on PR creation, but if the PR were closed, we'd have to delete any new files.  I'm leaning the latter; what do you think?
1. I believe so.  It'd be easy for the owner to approve since it'd be a file delete.
1. We might have to investigate further within the API to see how GitHub handles file renames from Git.
1. No, I think the CodeGovernor dashboard would be a good place to show their pending reviews.  That, or we could create an issue type with a `Pending Reviews` label, and assign it to the user, that is closed when the PR is closed/merged.
1. I don't think so?
1. I'd be okay with either, although I am leaning towards the latter, in order to reduce chatter in the PR thread.  We could also investigate creating an initial comment with, say, a status table, that is edited by CodeGovernor when somebody approves/rejects.  Thoughts?
